// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Belt_Array = require("@rescript/runtime/lib/js/Belt_Array.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

let StrataError = /* @__PURE__ */Primitive_exceptions.create("TrackerEngine.StrataError");

function parseJson(jsonString) {
  try {
    return JSON.parse(jsonString);
  } catch (exn) {
    throw {
      RE_EXN_ID: StrataError,
      _1: "Invalid JSON from native binding",
      Error: new Error()
    };
  }
}

function stringifyJson(json) {
  let string = JSON.stringify(json);
  if (string !== undefined) {
    return string;
  }
  throw {
    RE_EXN_ID: StrataError,
    _1: "Unable to stringify JSON",
    Error: new Error()
  };
}

function stringifyArray(items) {
  let strings = Belt_Array.map(items, stringifyJson);
  return "[" + Belt_Array.joinWith(strings, ",", s => s) + "]";
}

function compileTracker(dsl) {
  return parseJson(TrackerEngine.compileTracker(dsl));
}

function validateEvent(dsl, event) {
  let eventJson = stringifyJson(event);
  return parseJson(TrackerEngine.validateEvent(dsl, eventJson));
}

function compute(dsl, events, query) {
  let eventsJson = stringifyArray(events);
  let queryJson = stringifyJson(query);
  return parseJson(TrackerEngine.compute(dsl, eventsJson, queryJson));
}

function simulate(dsl, baseEvents, hypotheticals, query) {
  let baseJson = stringifyArray(baseEvents);
  let hypoJson = stringifyArray(hypotheticals);
  let queryJson = stringifyJson(query);
  return parseJson(TrackerEngine.simulate(dsl, baseJson, hypoJson, queryJson));
}

function suggest(dsl, events, planner) {
  let eventsJson = stringifyArray(events);
  return parseJson(TrackerEngine.suggest(dsl, eventsJson, planner));
}

exports.StrataError = StrataError;
exports.parseJson = parseJson;
exports.stringifyJson = stringifyJson;
exports.stringifyArray = stringifyArray;
exports.compileTracker = compileTracker;
exports.validateEvent = validateEvent;
exports.compute = compute;
exports.simulate = simulate;
exports.suggest = suggest;
/* No side effect */
